# Generated by Django 4.1 on 2025-01-31 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HospitalApp', '0004_tbl_packageservice'),
        ('GuestApp', '0004_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('require_date', models.DateField()),
                ('t_amount', models.IntegerField()),
                ('reason', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_customer')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.tbl_package')),
            ],
        ),
    ]
