# Generated by Django 4.1 on 2025-02-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerApp', '0003_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='commission',
            field=models.IntegerField(null=True),
        ),
    ]
