# Generated by Django 4.1 on 2025-02-24 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_customer'),
        ('HospitalApp', '0005_tbl_service_description'),
        ('CustomerApp', '0002_tbl_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('feedback', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_customer')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.tbl_package')),
            ],
        ),
    ]
