# Generated by Django 4.1 on 2025-01-20 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GuestApp', '0004_tbl_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('noofdays', models.IntegerField()),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_hospital')),
            ],
        ),
    ]
