# Generated by Django 4.1 on 2025-01-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_package',
            name='package_name',
            field=models.CharField(max_length=100),
        ),
    ]
