# Generated by Django 4.1 on 2025-01-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0003_tbl_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_packageservice',
            fields=[
                ('ps_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.tbl_package')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HospitalApp.tbl_service')),
            ],
        ),
    ]
