# Generated by Django 4.1 on 2025-01-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0002_tbl_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_login',
            name='status',
            field=models.CharField(default='', max_length=25),
        ),
    ]
