# Generated by Django 4.1 on 2025-01-21 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GuestApp', '0004_tbl_customer'),
        ('HospitalApp', '0002_alter_tbl_package_package_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_service',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('amount', models.IntegerField()),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_hospital')),
            ],
        ),
    ]
