# Generated by Django 4.1 on 2025-01-31 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HospitalApp', '0004_tbl_packageservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_service',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
