# Generated by Django 4.1 on 2025-01-15 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_tbl_location'),
        ('GuestApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_hospital',
            fields=[
                ('hospital_id', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('idproof', models.ImageField(upload_to='')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.tbl_location')),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GuestApp.tbl_login')),
            ],
        ),
    ]
